
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retailinventoryapi-api-1
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=RetailInventoryApi
      - Jwt__Audience=RetailInventoryClient
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  newman:
    image: postman/newman:alpine
    container_name: retailinventoryapi-newman-1
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./postman:/etc/newman
    command:
      run "Retail Inventory API.postman_collection.json" --delay-request 2000 --env-var baseUrl=http://api:80
